# Generated by Django 3.2.11 on 2022-04-07 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordofmouth', '0002_recipe_created_recipe_liked_recipe_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
