# Generated by Django 4.0.2 on 2022-03-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0003_remove_recipe_image_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='https://00f74ba44be772eaff20e514e449d70326a2b353e8-apidata.googleusercontent.com/download/storage/v1/b/a10-word-of-mouth/o/picture-of-golden-retriever-dog_0.webp?jk=AFshE3V0faWtCmn7uLA35Ib64BauZ5q62HpiS-p_i5dlb417N7eiZkwi8hqTmCs3pwHzcjTATmsJaAjy6nCurDHCIwhEe38DmmcomcGhWQlofpIaqg7TfhZ5dRgpA2DCp8f9WU4U2eEvc1sWnW35WqA_5ZjgV1X7egazBFVC6Nv9j2elE_tY9Z_ke2aJXf1AgR2mQcCWvIG4ioob3xd-MO57Zh53OZBbrk6FW2rka9mr-_Vgv8rbaf3HhK7hHtz3i6EBYN8-9e-UfWZ2O_1NHADlT_fl_qi4OasXVx1L-9RGaygOKZfYlwCy1LgJpUzhOSm0SOinMukKtDdzX3DgukUNWLEu3_27HkQ_aTgw1QcdlMX1NlcojRxCekd6pd7xM6Vh6VGuT-_b8UG0lk4cXuKAcBzJbYowE9X0y1whe7PQ8sIIFbQuGbF2iJ4Dc6grYKpC9WPR74JdB21dDruPkcceWiJI6LcB8AA7XTDfIetHeozO6dz3rDLpuoivouj4GiH1Sb5A7xqrfJsDZd4cB-MNP-JCLPtm4bu38l3l-uiFGURW4xvSI45TWkLFcWmpX7y_2qV_R2_lD5MIQeWG9aPRmjbQexO_u4ZcjkD_re8uaK0IXV_BP9pbWmdWXEFWnQxFKtzDILXjIlxPBD1-DvbPQ5zbfJbCp6A-1Rno3Ujt7PAj5ih6bP7wDz_kn74w4YpyAcXxkvgJ8jC0mgId_7p43HmQ6z5oeQxDQdZZ4gaPZf7RsesT47egDmz-GDyBGpfhj1KreveqnHYYTSlMm0rCXCqP8SziPsLhIYQelypU3Ozo6t_NaD3q236-y9PnJ8rGay1oegZ6SrbyUnciIDLY4_OWqyl9HKkv4eVcJm2dyM0-NPvx7SsGZOcfH6Ouy7MsUMqaEhMa2sIsprJJGPsVzYe4py1aLpkL-BnzxDfGKsnvqrsXutXurDH5s9gzWK_AuTLjDRal2ELHxmzOIyUxbE9fbor68TeFgW5EMu45XCFPrr5AcDyCb4mYc6BGK0YhwbCnDDRbSq9gvMd7YIpfwXb5MImrg9wcAECzanh5bDcCQJ451qAPlR7Z9j3KT_hS_xUx5UCf-ttq3xNQzdddUvHf7jrwSFzwCgSOoVMVWDVcTOQ-pH9Fe2sI&isca=1', max_length=200),
        ),
    ]
