# Generated by Django 4.0.2 on 2022-04-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0005_userrating_recipe_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
