# Generated by Django 4.0.2 on 2022-03-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0005_alter_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='https://storage.cloud.google.com/a10-word-of-mouth/picture-of-golden-retriever-dog_0.webp', max_length=1600),
        ),
    ]
