# Generated by Django 4.0.2 on 2022-04-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0005_comment'),
        ('wordofmouth', '0006_alter_userrating_id'),
    ]

    operations = [
    ]
