# Generated by Django 4.0.2 on 2022-03-28 01:31

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0006_alter_recipe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='https://storage.cloud.google.com/a10-word-of-mouth/picture-of-golden-retriever-dog_0.jpeg', storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='images/'),
        ),
    ]
