# Generated by Django 4.0.2 on 2022-03-28 01:32

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0007_remove_recipe_image_url_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='DEFAULT_URL', storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='images/'),
        ),
    ]
