# Generated by Django 4.0.2 on 2022-05-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0008_recipe_cook_time_recipe_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time_metric',
            field=models.CharField(default='minutes', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_metric',
            field=models.CharField(default='minutes', max_length=200),
        ),
    ]
