# Generated by Django 4.0.2 on 2022-03-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0009_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='image_url',
        ),
    ]
