# Generated by Django 4.0.2 on 2022-03-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0002_recipe_added_by'),
        ('wordofmouth', '0010_rename_image_recipe_image_url'),
    ]

    operations = [
    ]
