# Generated by Django 4.0.2 on 2022-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0011_tag_remove_recipe_cuisine_type_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='helloworld',
            field=models.IntegerField(default=0),
        ),
    ]
