# Generated by Django 4.0.2 on 2022-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0011_merge_20220329_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='text',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='make the recipe', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='parent',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
