# Generated by Django 4.0.2 on 2022-05-03 02:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('wordofmouth', '0013_remove_recipe_helloworld'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='r_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
