# Generated by Django 4.0.2 on 2022-05-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0014_recipe_r_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
